language: node_js
sudo: required

node_js:
  - "6.10"

services:
  - docker

env:
  global:

    # PAPERTRAIL_PORT
    - secure: "WFJk3vUsGO5LfGeksb4HKqdNrN1i0UdpOlkFiXAq7tRTulRPMzHsdVIJ0K4+sj6ly8ZpUhX4I+H+DALy7rA4+4fhrq1+MY/SJSAkq7Vd+jVEhlzLDU+E8u+iAQMxzdquxIidRtig5ubWzVN/LuFakGtskwiVwgzAiNraTY8nqKIobfdHsouvUyGYbDWk7mp+VPOD03zpxk9TmS1ma2E6sOeg6yDoaWZnpBmdxpXAt1+IwhA0+kCsQT7tpXFb61Ra7dul4Nfyf8E8aDnWqnNQIHqSMIykLP0fghQ5u0isrm5RIXzu8s/NaPOqY3VBnP5y79WneLPg+azfH7OtcIFkQH4IsCRPaSXUbzKXmjJhvIRWTOp/UxVFz9uTztey8j0i5noNtc191TvPt/183QuJJdSC7kSaUAbUQLFsQ2JjZcvvpHa3kXlf5LAXlnC/g1pvdEm16QE4bmjibWXhoyGd1x4r9W1yX29XVVK+ALXAn/v5c/2aA5hooIN3jFb8hWPjGpxFBulQQt/O5Tr8AB/mubQ8H/t0nJPpz+iQlaleVlSBDfsmXRcN9WOczbPddCCfdUOzfQPI8Wp2cwLfMyt+LnyFtOGxBReVadfmg57aErlJRcb9jEOlhO1CCwVaAMbqr4KRAylKcJCwKQchqTqgQhOwkGDu1AulcUjQn3/eNuE="

    # AWS_SECRET_ACCESS_KEY
    - secure: "DMFV9pUO8kO+87VnvoGA4tB8GZTOpis88oav0Kmy7YyFNRazmpsqLoBTLXA6bLDwNXHMOC93+H6Bpt3GNKrL3jBBLl7dqR4Hi/C+WxGX/gorT4h1XTXafiIJDtIpSV/brakJqgTSA9DBLiwJNf9vksmNZBgnNqmg6Io5lEfA3EL85OCUj6WsdB51+bNPp7R45LQOxCPeu0Hra+t6SgcUeJf5q2oT17zp/J2Qc97iCCzL1G+jjmE+8wQmBRjwCzZxYogLRjAfXf1onxHrf9j5HikWW/tL7PPhLDxWBoN+0bNcgszz4l0BwDnNr33QJVjyh1YnIEql2l2Q/7RyBLSC9L36hZ3BnXjswCdKUR0qVxPLfW0TrUWpL3BkYeyBUu5lxC4H20gn1KfSghY1/OyVhC5giFBzwmrgPrI7bbov961DSicB5A6EaU1HwJ5fKnhvuV6CkLJmwsTfy1WRdvtngFY8Opbj8/it7UDC1SBlVf+9Xn3FKlQEdc50iKzBSEq+H3wsiEV+p1YTMfJOmEcUy6y25gZjEin7zRGsasQ3WMeVUJIoCQonC6qhUxwoe2ufsPHMQQDOwl7NYzKloyfJs0KChuN/za8hsphxqfJ+adbMqrrh3RJFsEDPsctHB1vjwzGIXSbtSHuGJ8ECOi5rnDXbPPz8DU9A+owUZGLoPQ8="

    - PAPERTRAIL_HOST=logs6.papertrailapp.com
    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - LAMBDA_NAME=cloudwatchToPapertrail

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:

  - yarn lint
  - make test

  - pip install awscli --upgrade --user

deploy:

  - provider: script
    script: export AWS_DEFAULT_REGION=ap-southeast-2 && make deploy
    skip_cleanup: true
    on:
      branch: chromatix

  - provider: script
    script: export AWS_DEFAULT_REGION=us-west-2 && make deploy
    skip_cleanup: true
    on:
      branch: chromatix

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
