language: node_js
sudo: required

node_js:
  - "6.10"

services:
  - docker

env:
  global:

    # PAPERTRAIL_PORT
    - secure: "JGGUfYxlAsxJTY+C6GPio/7zsDW8182sTLHjiymP6v3wyeMAI5BTviSHK+tpz283SYNyrmxZ1z6SwU0o/HxltgoWpkImUd0qeRvjAOzo8c0oht9Ke0fuoYIRhXqCLCRvvcczSKhTHe99cbb31I9F8fZMiJ32odcg1qa1LDOi3vuvPtoJN9qn+cFJsdIvWQiWP7n/poYdpWbISf8D786D6OY+D8e13NzMnx3x+dHRlgw2cV3T2xxsu3I1vhegDqwAVjCiire5FgGtSJ3Ya9xU7Hv7O2Za5wEM66N0wRvhZBEZ7VuKWuAkmR0rQ6gZGmnRlnYq94WgmJJb3vlu65CbpWqWjyaRjxlK0YJkX4r2q05TDB2SwQgRd+/UmBJT1b1+3lL9kAdDblVu2WRDF/HAEfSaLMC0A+p0oLXu9FbEW9KjzgkEiYDqd+MdMNSW1NnNRAc4JW+4yVftY1bgkNjkKiH8IoKYullqOGK8i68So/jwxjAV2Vu/e0oTcZVRpuum/kIWk9cgQfQ1VtoAElQyHtk/V2kqcMLTbMgJsvRKMoeeAYENI+oJhWBNwPnumYh7R1iyKCUofRSclRCIOw7DsDJrSFJQrrPZ8nDMzTYsDwfOeEas2UqzJNFIrXHLPQQAAdmvA4O90cfT9c7bJ9N4VE02ElKL3kXWhbvd+pGGqQE="

    # AWS_SECRET_ACCESS_KEY
    - secure: "Zzs4X0P3LpMqJX3mmjwP6KOUb1HactoIy0D5lORIUE9UT9g4mxnfDUxvaBAVwH+96PBEl4EDEDIazdk+5uBVjUOd//z1kKspg5vkLDYxLg5GkKF5fmxP7bULpOf1CwCor+PYYp/Fv1W3CcbU83uKlvOcD1zfhRQ7y6yJx0geuiZtXGNLbmlRFF7jZbhFh0siwgcivDVYxXN8lc9fgTTeun8RqHH8MyfBNTyH/daNYeId7IjalI3dK6Jm5z+s9zcE2ZtVndQ0B8nGjR21eKc+2P89tXHnFCeu0EvPOJj+C0hzQ1I/E/Qyh1fqwgKcNUK1MgsdsqEv2J0rS3ecaABcc/TpopteEeSabtanukY2SLLIy1LSYme3w+CmPo5f74yqAD0Nt3Ui3WQ9lJ+W3p9aPVE3Fysjd8ZCRsMZ0iOBJq7PUnZk3TfSte43VkSAQYsVQUGcHOKEXEaLFd9FA9YktSWLBBQgdna6LVP3F4q+JcKj0YfvyKsDRP5FYDdrRncKBE3lxLJa+K2aXdAlj4KnV30YFjmrOQmZ2TGlHUf+C36NOnYupclUI5Ka16g+WJB9I4yk/J6TQKqasuYGYMqCPEyDDPA3Ul3vXwoziIO+V/4Dno5W9WHcsI+lLMDncs8G7ZHgYhbejCEYjTdL0k0RlGQtJFu6QVXJ5MSlzk1R0Mk="

    - PAPERTRAIL_HOST=logs6.papertrailapp.com
    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - LAMBDA_NAME=cloudwatchToPapertrail
    - AWS_DEFAULT_REGION=ap-southeast-2

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn lint
  - make test

deploy:
  - provider: script
    script: pip install awscli --upgrade --user && make deploy
    skip_cleanup: true
    on:
      branch: chromatix

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
